ParquetFiles
deephaven/deephaven-core-test-data pull request #1
Opened 2021-06-30 18:13 UTC by hythloda

2021-06-30 19:08 UTC, jcferretti approved these changes, later dismissed

2021-07-02 16:23 UTC, chipkent requested changes

2021-07-02 16:23 UTC, chipkent commented on README.md
> +1. Follow the README instructions on [Deephaven Community Core](https://github.com/deephaven/deephaven-core) for installing the OSS client and all required dependencies.
```suggestion
1. Follow the README instructions on [Deephaven Community Core](https://github.com/deephaven/deephaven-core) for installing the client and all required dependencies.
```
Avoiding religious arguments.

2021-07-02 16:23 UTC, chipkent commented on README.md
> +
Repo needs a license.  Set it as Apache 2.0, unless it will be 100% data.  Then use CCL.  Add a note about the license in the readme.

2021-07-06 14:24 UTC, chipkent approved these changes

2021-07-06 14:25 UTC, merged